### ISSUE TITLE
Alignment not allowed error when running ssm-session --list

### ISSUE THREAD

**Issue by avaitla** [mludvig/aws-ssm-tools#13]
I've noticed that if there is no tag called Name on an instance this error is thrown:

```
Traceback (most recent call last):
  File "/usr/local/bin/ssm-session", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/ssm_tools/ssm_session_cli.py", line 81, in main
    InstanceResolver(args).print_list()
  File "/usr/local/lib/python3.7/site-packages/ssm_tools/resolver.py", line 103, in print_list
    print(f"{item['InstanceId']}   {item['HostName']:{hostname_len}}   {item['InstanceName']:{instname_len}}   {' '.join(item['Addresses'])}")
ValueError: '=' alignment not allowed in string format specifier
```

Might be helpful to have a more informative error message.

**Comment by mludvig** [comment]
Fixed in #16
