### ISSUE TITLE
KeyError: 'Tags' when an instance without tags is present

### ISSUE THREAD

**Issue by jynolen** [mludvig/aws-ssm-tools#22]
Hello,

We figure out that is an instance rans without tags associated to it, it generates the following error:

```
Traceback (most recent call last):
  File "/home/jynolen/.local/bin/ssm-session", line 8, in <module>
    sys.exit(main())
  File "/home/jynolen/.local/lib/python3.8/site-packages/ssm_tools/ssm_session_cli.py", line 105, in main
    InstanceResolver(args).print_list()
  File "/home/jynolen/.local/lib/python3.8/site-packages/ssm_tools/resolver.py", line 122, in print_list
    items = self.get_list().values()
  File "/home/jynolen/.local/lib/python3.8/site-packages/ssm_tools/resolver.py", line 93, in get_list
    for tag in instance['Tags']:
KeyError: 'Tags'
```

**Comment by jynolen** [comment]
Outdate version of my lib sry
