### ISSUE TITLE
not working in windows os

### ISSUE THREAD

**Issue by vadirajks** [mludvig/aws-ssm-tools#39]
Please help me know if anything i need to do to fix this.

```
C:\Users\Administrator>ec2-session --list --region ap-south-1 --profile vtest
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Scripts\ec2-session.exe\__main__.py", line 4, in <module>
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\ssm_tools\ssm_session_cli.py", line 30, in <module>
    signal.signal(signal.SIGTSTP, signal.SIG_IGN)  # Ignore Ctrl-Z - pass it on to the shell
                  ^^^^^^^^^^^^^^
AttributeError: module 'signal' has no attribute 'SIGTSTP'

```

**Comment by mludvig** [comment]
Fixed in aws-ssm-tools 1.5.1
